/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basisdatagemink;

/**
 *
 * @author Rama
 */
public class Admin_Page extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Page
     */
    public Admin_Page() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDaftarpegawai = new javax.swing.JButton();
        btnDaftarpembeli = new javax.swing.JButton();
        btnDaftarpesanan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnDaftardb = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnDaftarbahan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnDaftarmenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnDaftarkartumember = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnDaftarpembayaran = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setText("Daftar Pegawai");

        jLabel2.setText("Daftar Pembeli");

        jLabel3.setText("Daftar Pesanan");

        btnDaftarpegawai.setText("Go");
        btnDaftarpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarpegawaiActionPerformed(evt);
            }
        });

        btnDaftarpembeli.setText("Go");
        btnDaftarpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarpembeliActionPerformed(evt);
            }
        });

        btnDaftarpesanan.setText("Go");
        btnDaftarpesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarpesananActionPerformed(evt);
            }
        });

        jLabel4.setText("Daftar Delivery Boy");

        btnDaftardb.setText("Go");
        btnDaftardb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftardbActionPerformed(evt);
            }
        });

        jLabel5.setText("Daftar Bahan Baku");

        btnDaftarbahan.setText("Go");
        btnDaftarbahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarbahanActionPerformed(evt);
            }
        });

        jLabel6.setText("Daftar Menu");

        btnDaftarmenu.setText("Go");
        btnDaftarmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarmenuActionPerformed(evt);
            }
        });

        jLabel7.setText("Daftar Kartu Member");

        btnDaftarkartumember.setText("Go");
        btnDaftarkartumember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarkartumemberActionPerformed(evt);
            }
        });

        jLabel8.setText("Daftar Pembayaran");

        btnDaftarpembayaran.setText("Go");
        btnDaftarpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarpembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(1, 1, 1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDaftarpegawai)
                                    .addComponent(jLabel1)))
                            .addComponent(jLabel2)
                            .addComponent(btnDaftarpembeli)
                            .addComponent(btnDaftarpesanan))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDaftarmenu)
                            .addComponent(btnDaftarbahan)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(btnDaftardb)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btnDaftarkartumember)
                            .addComponent(jLabel8)
                            .addComponent(btnDaftarpembayaran)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftarpegawai)
                    .addComponent(btnDaftardb)
                    .addComponent(btnDaftarkartumember))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftarpembeli)
                    .addComponent(btnDaftarbahan)
                    .addComponent(btnDaftarpembayaran))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftarpesanan)
                    .addComponent(btnDaftarmenu))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new Main_Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDaftarpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarpegawaiActionPerformed
        dispose();
        new Pegawai().setVisible(true);
    }//GEN-LAST:event_btnDaftarpegawaiActionPerformed

    private void btnDaftarpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarpembeliActionPerformed
        dispose();
        new Pembeli().setVisible(true);
    }//GEN-LAST:event_btnDaftarpembeliActionPerformed

    private void btnDaftarpesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarpesananActionPerformed
        dispose();
        new Pesanan().setVisible(true);
    }//GEN-LAST:event_btnDaftarpesananActionPerformed

    private void btnDaftardbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftardbActionPerformed
        dispose();
        new Delivery_Boy().setVisible(true);
    }//GEN-LAST:event_btnDaftardbActionPerformed

    private void btnDaftarbahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarbahanActionPerformed
        dispose();
        new Bahan_Baku().setVisible(true);
    }//GEN-LAST:event_btnDaftarbahanActionPerformed

    private void btnDaftarmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarmenuActionPerformed
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_btnDaftarmenuActionPerformed

    private void btnDaftarkartumemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarkartumemberActionPerformed
        dispose();
        new Kartu_Member().setVisible(true);
    }//GEN-LAST:event_btnDaftarkartumemberActionPerformed

    private void btnDaftarpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarpembayaranActionPerformed
        dispose();
        new Pembayaran().setVisible(true);
    }//GEN-LAST:event_btnDaftarpembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftarbahan;
    private javax.swing.JButton btnDaftardb;
    private javax.swing.JButton btnDaftarkartumember;
    private javax.swing.JButton btnDaftarmenu;
    private javax.swing.JButton btnDaftarpegawai;
    private javax.swing.JButton btnDaftarpembayaran;
    private javax.swing.JButton btnDaftarpembeli;
    private javax.swing.JButton btnDaftarpesanan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
